### ISSUE TITLE
Requiring both magento2-replace-bundled and magento2-replace-graphql conflict.

### ISSUE THREAD

**Issue by reense** [yireo/magento2-replace-graphql#20]
Hello,

First of all, thanks for these packages! I think I found a conflict in these packages.
I've required magento2-replace-bundled first; after that I've ran:
`composer2 require yireo/magento2-replace-graphql:4.2.3`. However, I'm getting this message:
```
Problem 1
    - yireo/magento2-replace-bundled is locked to version 4.3.1 and an update of this package was not requested.
    - yireo/magento2-replace-graphql[4.2.3] cannot be installed as that would require removing yireo/magento2-replace-bundled[4.3.1]. They both replace klarna/module-kp-graph-ql and thus cannot coexist.
    - Root composer.json requires yireo/magento2-replace-graphql 4.2.3 -> satisfiable by yireo/magento2-replace-graphql[4.2.3].
   ```

Shouldn't klarna/module-kp-graph-ql only be part of the replace-graphql package? Let me know what you think; if needed I can create a PR.

**Comment by jissereitsma** [comment]
Actually this is a known conflict and it is there by design. If one would replace the Klarna main modules but not the Klarna GraphQL counterparts, the Klarna GraphQL module would cause errors during DI compile. So unfortunately, the only way to maintain both replacement repositories is to have duplicates. The magento2-replace-all is one example where everything is combined so no duplicates exist. What most people do is use the bundled replacement package, and then replace the GraphQL packages in the main `composer.json` file by copying-and-pasting.

**Comment by jissereitsma** [comment]
I'm closing this ticket due to inactivity.
